### ISSUE TITLE
Q: Windows端Clash，代理启用报错

### ISSUE THREAD

**Issue by likemuuxi** [NiceVPN123/NiceVPN#25]
### 详细说明

```bash
什么: Windows端Clash，代理启用报错
怎么: Could not switch to this profile!
proxy 387: ss 139.162.59.135:443 obfs mode error: /herhero6
为什么: 请问如何解决这个问题
```

### 这里有一些承诺需要审阅

- [ ] 我会广泛传播这个项目
- [X] 这是我经过思考提出的问题
- [X] 我查阅了其他的issues，没有重复提问
- [X] 我承诺遵守社区指导方针

**Comment by Burgerdash** [comment]
你配置文件里面的这个节点：139.162.59.135:443可能挂了，要么换配置，要么右键编辑将对应的那个节点注释掉（还有后面group里用到这个节点的地方），然后应该就能切换到这个节点了
